# Test your FastAPI endpoints

#POST http://localhost:8000/createTournament
###
POST http://localhost:8000/createTournament
Accept: application/json

{
  "name": "Torneo di prova2",
  "code": "TP011",
  "tables": [1, 2, 3, 4]
}

###
GET http://localhost:8000/tournaments

###
POST http://localhost:8000/joinTournament?code=TP001
Accept: application/json

{
    "name": "Federico",
    "player_id": 1234
}